version: "3.3"
services:
  azure-sql-edge:
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Banana123
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
    ports:
      - "1433:1433"
    container_name: azure-sql-edge
    image: mcr.microsoft.com/azure-sql-edge
